#! /usr/bin/env bash
#
# Replace volatile Zeek observation timestamps while preserving protocol timestamps.

awk -F '\t' 'BEGIN { OFS = "\t" }
    /^#open[[:space:]]/ {
        print "#open XXXX-XX-XX-XX-XX-XX";
        next;
    }
    /^#close[[:space:]]/ {
        print "#close XXXX-XX-XX-XX-XX-XX";
        next;
    }
    $1 ~ /^[0-9][0-9]*\.[0-9][0-9]*$/ {
        $1 = "XXXXXXXXXX.XXXXXX";
        print;
        next;
    }
    { print }'
